import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, test } from "vitest";
import { filesUnder } from "./support/repo.ts";

const corpus = join(import.meta.dirname, "corpus");

describe("the corpus keeps its bytes", () => {
  test("the corpus holds 32 realistic documents and 672 GFM spec examples", () => {
    expect(filesUnder(join(corpus, "realistic"), /\.md$/)).toHaveLength(32);
    expect(filesUnder(join(corpus, "spec"), /\.md$/)).toHaveLength(672);
  });

  test("no fixture was given CRLF line endings by a checkout", () => {
    // Fixtures are written with LF; CRLF variants are generated by the tests. See .gitattributes.
    const converted = filesUnder(corpus, /\.md$/).filter((f) => readFileSync(f, "utf8").includes("\r"));
    expect(converted).toEqual([]);
  });
});
